add_newline = false
command_timeout = 2000
continuation_prompt = "▶▶"
format = "$username$hostname$directory$status$line_break$character$all"
right_format = "$git_status$git_state$git_branch$cmd_duration$time"

[character]
success_symbol = "[➜](bold bright-green)"

[directory]
home_symbol = "~"
truncation_length = 8
truncate_to_repo = true
truncation_symbol = "../"
read_only = "🔒"
style = "#c383eF"

[package]
disabled = true

[status]
format = "[$symbol$status=$common_meaning$signal_name$maybe_int]($style)"
map_symbol = true
disabled = false
symbol = "🔴"

[username]
show_always = true
format = "[$user]($style)"
style_root = "bold red"
style_user = "cyan"

[hostname]
ssh_only = false
format = "[@](green)[$hostname](yellow) "
disabled = false

[cmd_duration]
min_time = 100
show_milliseconds = true
format = "[$duration]($style) "

[git_branch]
always_show_remote = true
format = "[$symbol$remote_branch]($style) "
style = "blue"

[time]
format = "[ $time](#bb9966)"
time_format = "%R:%S"
disabled = false

[kubernetes]
disabled = true

[shell]
disabled = true
bash_indicator = "󱆃"
style = "yellow bold"

[battery]
disabled = true

[battery.display]
threshold = 30
style = "bold red"
disabled = true

[nix_shell]
symbol = " "

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'
Unknown = '󰠥'
